export const TODO_APP_ITEM_EDITING_STARTED = 'TODO_APP_ITEM_EDITING_STARTED';
export const TODO_APP_ITEM_EDITING_CANCELLED = 'TODO_APP_ITEM_EDITING_CANCELLED';
export const TODO_APP_SET_VISIBILITY_FILTER = 'TODO_APP_SET_VISIBILITY_FILTER';

export const TODO_APP_LOADING_STARTED = 'TODO_APP_LOADING_STARTED';
export const TODO_APP_LOADING_SUCCESS = 'TODO_APP_LOADING_SUCCESS';

export const TODO_APP_ITEM_UPDATE_STARTED = 'TODO_APP_ITEM_UPDATE_STARTED';
export const TODO_APP_ITEM_UPDATE_SUCCESS = 'TODO_APP_ITEM_UPDATE_SUCCESS';

export const TODO_APP_ITEM_CREATE_STARTED = 'TODO_APP_ITEM_CREATE_STARTED';
export const TODO_APP_ITEM_CREATE_SUCCESS = 'TODO_APP_ITEM_CREATE_SUCCESS';

export const TODO_APP_ITEM_DELETE_COMPLETE_STARTED = 'TODO_APP_ITEM_DELETE_COMPLETE_STARTED';
export const TODO_APP_ITEM_DELETE_COMPLETE_SUCCESS = 'TODO_APP_ITEM_DELETE_COMPLETE_SUCCESS';
