export const TODO_APP_ITEM_CREATE = 'TODO_APP_ITEM_CREATE';
export const TODO_APP_ITEM_UPDATE = 'TODO_APP_ITEM_UPDATE';
export const TODO_APP_ITEM_TOGGLE = 'TODO_APP_ITEM_TOGGLE';
export const TODO_APP_ITEM_EDITING_STARTED = 'TODO_APP_ITEM_EDITING_STARTED';
export const TODO_APP_ITEM_EDITING_CANCELLED = 'TODO_APP_ITEM_EDITING_CANCELLED';
export const TODO_APP_SET_VISIBILITY_FILTER = 'TODO_APP_SET_VISIBILITY_FILTER';

export const TODO_APP_LOADING_STARTED = 'TODO_APP_LOADING_STARTED';
export const TODO_APP_LOADING_SUCCESS = 'TODO_APP_LOADING_SUCCESS';
